# Generated by Django 2.1.7 on 2019-04-01 14:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190401_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 1, 14, 59, 11, 348514, tzinfo=utc)),
        ),
    ]
