# Generated by Django 2.1.7 on 2019-04-01 17:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190401_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 1, 17, 47, 52, 955853, tzinfo=utc)),
        ),
    ]
